name: hunch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.7.3+1
  video_player: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/hunch_logo.jpeg
  fonts:
    - family: HubotSans
      fonts:
        - asset: assets/fonts/HubotSans-Medium.ttf
